[project]
name = 'stax-poll-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.carbon-credit-retirement]
path = 'contracts/carbon-credit-retirement.clar'
[contracts.carbon-marketplace]
path = 'contracts/carbon-marketplace.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
