[project]
name = 'staxpoll-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.carbon-credit-marketplace]
path = 'contracts/carbon-credit-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.carbon-credit-token]
path = 'contracts/carbon-credit-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.carbon-credit-verification]
path = 'contracts/carbon-credit-verification.clar'
clarity_version = 1
epoch = 2.05

[contracts.carbon-retirement]
path = 'contracts/carbon-retirement.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.revenue-sharing]
path = 'contracts/revenue-sharing.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
